/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MechanicService } from "../mechanic.service";
import { MechanicCreateInput } from "./MechanicCreateInput";
import { Mechanic } from "./Mechanic";
import { MechanicFindManyArgs } from "./MechanicFindManyArgs";
import { MechanicWhereUniqueInput } from "./MechanicWhereUniqueInput";
import { MechanicUpdateInput } from "./MechanicUpdateInput";

export class MechanicControllerBase {
  constructor(protected readonly service: MechanicService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Mechanic })
  async createMechanic(
    @common.Body() data: MechanicCreateInput
  ): Promise<Mechanic> {
    return await this.service.createMechanic({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Mechanic] })
  @ApiNestedQuery(MechanicFindManyArgs)
  async mechanics(@common.Req() request: Request): Promise<Mechanic[]> {
    const args = plainToClass(MechanicFindManyArgs, request.query);
    return this.service.mechanics({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Mechanic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async mechanic(
    @common.Param() params: MechanicWhereUniqueInput
  ): Promise<Mechanic | null> {
    const result = await this.service.mechanic({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Mechanic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMechanic(
    @common.Param() params: MechanicWhereUniqueInput,
    @common.Body() data: MechanicUpdateInput
  ): Promise<Mechanic | null> {
    try {
      return await this.service.updateMechanic({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Mechanic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMechanic(
    @common.Param() params: MechanicWhereUniqueInput
  ): Promise<Mechanic | null> {
    try {
      return await this.service.deleteMechanic({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
