/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MontirService } from "../montir.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MontirCreateInput } from "./MontirCreateInput";
import { Montir } from "./Montir";
import { MontirFindManyArgs } from "./MontirFindManyArgs";
import { MontirWhereUniqueInput } from "./MontirWhereUniqueInput";
import { MontirUpdateInput } from "./MontirUpdateInput";
import { CustomerOrderFindManyArgs } from "../../customerOrder/base/CustomerOrderFindManyArgs";
import { CustomerOrder } from "../../customerOrder/base/CustomerOrder";
import { CustomerOrderWhereUniqueInput } from "../../customerOrder/base/CustomerOrderWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MontirControllerBase {
  constructor(
    protected readonly service: MontirService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Montir })
  @nestAccessControl.UseRoles({
    resource: "Montir",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMontir(@common.Body() data: MontirCreateInput): Promise<Montir> {
    return await this.service.createMontir({
      data: data,
      select: {
        createdAt: true,
        id: true,
        montirName: true,
        montirPassword: true,
        montirPhone: true,
        section: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Montir] })
  @ApiNestedQuery(MontirFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Montir",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async montirs(@common.Req() request: Request): Promise<Montir[]> {
    const args = plainToClass(MontirFindManyArgs, request.query);
    return this.service.montirs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        montirName: true,
        montirPassword: true,
        montirPhone: true,
        section: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Montir })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Montir",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async montir(
    @common.Param() params: MontirWhereUniqueInput
  ): Promise<Montir | null> {
    const result = await this.service.montir({
      where: params,
      select: {
        createdAt: true,
        id: true,
        montirName: true,
        montirPassword: true,
        montirPhone: true,
        section: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Montir })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Montir",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMontir(
    @common.Param() params: MontirWhereUniqueInput,
    @common.Body() data: MontirUpdateInput
  ): Promise<Montir | null> {
    try {
      return await this.service.updateMontir({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          montirName: true,
          montirPassword: true,
          montirPhone: true,
          section: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Montir })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Montir",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMontir(
    @common.Param() params: MontirWhereUniqueInput
  ): Promise<Montir | null> {
    try {
      return await this.service.deleteMontir({
        where: params,
        select: {
          createdAt: true,
          id: true,
          montirName: true,
          montirPassword: true,
          montirPhone: true,
          section: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/customerOrders")
  @ApiNestedQuery(CustomerOrderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CustomerOrder",
    action: "read",
    possession: "any",
  })
  async findCustomerOrders(
    @common.Req() request: Request,
    @common.Param() params: MontirWhereUniqueInput
  ): Promise<CustomerOrder[]> {
    const query = plainToClass(CustomerOrderFindManyArgs, request.query);
    const results = await this.service.findCustomerOrders(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        location: true,

        montir: {
          select: {
            id: true,
          },
        },

        problem: true,

        service: {
          select: {
            id: true,
          },
        },

        status: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/customerOrders")
  @nestAccessControl.UseRoles({
    resource: "Montir",
    action: "update",
    possession: "any",
  })
  async connectCustomerOrders(
    @common.Param() params: MontirWhereUniqueInput,
    @common.Body() body: CustomerOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customerOrders: {
        connect: body,
      },
    };
    await this.service.updateMontir({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/customerOrders")
  @nestAccessControl.UseRoles({
    resource: "Montir",
    action: "update",
    possession: "any",
  })
  async updateCustomerOrders(
    @common.Param() params: MontirWhereUniqueInput,
    @common.Body() body: CustomerOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customerOrders: {
        set: body,
      },
    };
    await this.service.updateMontir({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/customerOrders")
  @nestAccessControl.UseRoles({
    resource: "Montir",
    action: "update",
    possession: "any",
  })
  async disconnectCustomerOrders(
    @common.Param() params: MontirWhereUniqueInput,
    @common.Body() body: CustomerOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customerOrders: {
        disconnect: body,
      },
    };
    await this.service.updateMontir({
      where: params,
      data,
      select: { id: true },
    });
  }
}
