/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Montir as PrismaMontir,
  CustomerOrder as PrismaCustomerOrder,
} from "@prisma/client";

export class MontirServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.MontirCountArgs, "select">): Promise<number> {
    return this.prisma.montir.count(args);
  }

  async montirs<T extends Prisma.MontirFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.MontirFindManyArgs>
  ): Promise<PrismaMontir[]> {
    return this.prisma.montir.findMany<Prisma.MontirFindManyArgs>(args);
  }
  async montir<T extends Prisma.MontirFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.MontirFindUniqueArgs>
  ): Promise<PrismaMontir | null> {
    return this.prisma.montir.findUnique(args);
  }
  async createMontir<T extends Prisma.MontirCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MontirCreateArgs>
  ): Promise<PrismaMontir> {
    return this.prisma.montir.create<T>(args);
  }
  async updateMontir<T extends Prisma.MontirUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MontirUpdateArgs>
  ): Promise<PrismaMontir> {
    return this.prisma.montir.update<T>(args);
  }
  async deleteMontir<T extends Prisma.MontirDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.MontirDeleteArgs>
  ): Promise<PrismaMontir> {
    return this.prisma.montir.delete(args);
  }

  async findCustomerOrders(
    parentId: string,
    args: Prisma.CustomerOrderFindManyArgs
  ): Promise<PrismaCustomerOrder[]> {
    return this.prisma.montir
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .customerOrders(args);
  }
}
