/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CustomerOrderService } from "../customerOrder.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CustomerOrderCreateInput } from "./CustomerOrderCreateInput";
import { CustomerOrder } from "./CustomerOrder";
import { CustomerOrderFindManyArgs } from "./CustomerOrderFindManyArgs";
import { CustomerOrderWhereUniqueInput } from "./CustomerOrderWhereUniqueInput";
import { CustomerOrderUpdateInput } from "./CustomerOrderUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CustomerOrderControllerBase {
  constructor(
    protected readonly service: CustomerOrderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CustomerOrder })
  @nestAccessControl.UseRoles({
    resource: "CustomerOrder",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCustomerOrder(
    @common.Body() data: CustomerOrderCreateInput
  ): Promise<CustomerOrder> {
    return await this.service.createCustomerOrder({
      data: {
        ...data,

        montir: data.montir
          ? {
              connect: data.montir,
            }
          : undefined,

        service: data.service
          ? {
              connect: data.service,
            }
          : undefined,

        status: data.status
          ? {
              connect: data.status,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,

        vehicle: data.vehicle
          ? {
              connect: data.vehicle,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        location: true,

        montir: {
          select: {
            id: true,
          },
        },

        problem: true,

        service: {
          select: {
            id: true,
          },
        },

        status: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CustomerOrder] })
  @ApiNestedQuery(CustomerOrderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CustomerOrder",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerOrders(
    @common.Req() request: Request
  ): Promise<CustomerOrder[]> {
    const args = plainToClass(CustomerOrderFindManyArgs, request.query);
    return this.service.customerOrders({
      ...args,
      select: {
        createdAt: true,
        id: true,
        location: true,

        montir: {
          select: {
            id: true,
          },
        },

        problem: true,

        service: {
          select: {
            id: true,
          },
        },

        status: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CustomerOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerOrder",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerOrder(
    @common.Param() params: CustomerOrderWhereUniqueInput
  ): Promise<CustomerOrder | null> {
    const result = await this.service.customerOrder({
      where: params,
      select: {
        createdAt: true,
        id: true,
        location: true,

        montir: {
          select: {
            id: true,
          },
        },

        problem: true,

        service: {
          select: {
            id: true,
          },
        },

        status: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CustomerOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerOrder",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCustomerOrder(
    @common.Param() params: CustomerOrderWhereUniqueInput,
    @common.Body() data: CustomerOrderUpdateInput
  ): Promise<CustomerOrder | null> {
    try {
      return await this.service.updateCustomerOrder({
        where: params,
        data: {
          ...data,

          montir: data.montir
            ? {
                connect: data.montir,
              }
            : undefined,

          service: data.service
            ? {
                connect: data.service,
              }
            : undefined,

          status: data.status
            ? {
                connect: data.status,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,

          vehicle: data.vehicle
            ? {
                connect: data.vehicle,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          location: true,

          montir: {
            select: {
              id: true,
            },
          },

          problem: true,

          service: {
            select: {
              id: true,
            },
          },

          status: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          vehicle: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CustomerOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerOrder",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCustomerOrder(
    @common.Param() params: CustomerOrderWhereUniqueInput
  ): Promise<CustomerOrder | null> {
    try {
      return await this.service.deleteCustomerOrder({
        where: params,
        select: {
          createdAt: true,
          id: true,
          location: true,

          montir: {
            select: {
              id: true,
            },
          },

          problem: true,

          service: {
            select: {
              id: true,
            },
          },

          status: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          vehicle: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
